# Generated by Django 6.0 on 2025-12-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text="Duration of the course (e.g. '4 Weeks', '10 Hours')", max_length=50, null=True),
        ),
    ]
